apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mankahi
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  JWT_ACCESS_EXPIRES_IN: "${JWT_ACCESS_EXPIRES_IN}"
  JWT_REFRESH_EXPIRES_IN: "${JWT_REFRESH_EXPIRES_IN}"
  SESSION_SECRET: "${SESSION_SECRET}"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
  ELASTICSEARCH_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: mankahi
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_MULTIPLE_DATABASES: "${POSTGRES_MULTIPLE_DATABASES}"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: mankahi
type: Opaque
stringData:
  REDIS_URL: "${REDIS_URL}"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: mankahi
type: Opaque
stringData:
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
  namespace: mankahi
type: Opaque
stringData:
  ELASTICSEARCH_USERNAME: "${ELASTICSEARCH_USERNAME}"
  ELASTICSEARCH_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
