$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress
  namespace: mankahi
---
$patch: delete
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-config
  namespace: mankahi
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: mankahi
---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: mankahi
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress
