---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-s3-secret
  namespace: mankahi
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA5RLJKH2L96yEUwyqPWH9vZwSqU5k9KQj63ZyKOL2bQ9hEtxMHsTeP4T52JQpEUVJKUXT7mIBKfcnx7iiSUwYCh4/FKxqqpt85nwKYkphj+Iom3yCnVkgKiTHAdwm7nZFbEMDZywhYLpnR+QkNZEN0XoKsO7MqEIAnWUx3kQd16DvfDeZ+nGYPq9iWhu9r0KPTrHeUQqmG+ylg49tyaXftHqMq91w8jJJayJLgY6z40xdocum2ONXG1VTd1ABZli7NpO7U3vFZ7wauVF7UWxQAkHMqfze06ajYMc2pr7mQ0uwfEqDvB30t1lgUVczhG8Prz92EqQpjIJ468CxQzwDuyocA/flNdnUYBnIwfPQdMstlzTCGwE2bg/HXwrr4s/mXvyD5YrYI1E0F+UAai1rOvVly6DwexP+Z3OwJiChxHV9wTZVmhXzh9iTbod/KIvSL4TCJCdkmxvJ5LjlV5JHJUy6TQZpOs+vGgdlez+uz+jTAy9RlfWXCyDONTq5iMyQ04IW6s87dQ9xD2tBwOiVzT4LbF4wTtyPE5fyJciwQHCFB+EyiyqdlYXiCmpOT0lik7gyazE8Xj2fpbRJbXxqghb6lJ3GxI4hPP7vWmqeWNWeb3kfJh/vj8Z1qzddjAmmBCFmV35ohCDIxbH00BDdgPl3RSfgL8Hcm+UBa3SYsWE4TA7r8GsE6H33xpFvwHg4rKadm4/PgJA2AcUgUV0O9/kzHI3jCV4CdEjCgyO4YxMo4w4s1XCYc
    AWS_SECRET_ACCESS_KEY: AgATsFR+x+X/ECC5HLz4NPArx8GAmbO7H33YWD1TtPZNHpZJwZYtK3JsbRdOKWGzRCdQsTJnu+lj6CfnA5eD8H1Abe54LdPbpsVYfDLNO8iX7iiz7pVDq6xDBE/Hr2kR/ZZUdtX+uvH+9x190Z453UXW7baall8vM4MrR4AdTcA5kGc5OklD9Y9195uAkQHHGr4xnlDnRfJ+4j/jm8ck3dllF3waAD3qbXvLKjKyGs7zNf2Gig2HFAL5pFZuDcqsYE13JHy/86homaZCxMOddfU8zv/yqQrQYEHmiyWPZ/nMU/eAGxyExIpWYKCbENcgTwiOMzKxpmtSe8v1ggqI4Rc2XURJNOyXK9ecVl80hCcuTCJZVB4o3jVRabxVIFiTuQwQyGzd36OsR3DDL4UsU7uPnq65L1ebSGE9crF+2e2jQG9fem5oCbnPugijt+nZO+clAHMGeTZ5vMgew/1BjKOz8i4k8YZk9whai1zpVaOYyphsHkkKb3sqOjOH29yPg3W0gv+0Gwxsp/TtEV7M990QJaOAcsPb5qBMY0LxhVAW5NlZApbvTI5HHn6s3FKNbw94G7kzLXLyeJiYnOkoAjV7Jn6ygML6bIX017gluh4/SHUTvNCeb8iheE6O4bAaEYUGL0nTsBJA9QV108JYug+RTTOxWatmpDTqT1mtVWIIk7QmlkPHlez8Iqteuow7VbIgXxnQDDvSiYw3SMcum01obX4IOF/dSgqbP1pXd7Vd/4vs3+pazI4pFjd5Ug==
  template:
    metadata:
      name: backup-s3-secret
      namespace: mankahi
    type: Opaque
