---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: mankahi
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBR/VNvQS7iORphPP6rMNXVFcExd+GMNLI+26173j0qQmnOz8DgW1DwvzPU5wNSpZ7RBZ7MjCgpDYO5JWjmS706jX/oRBG5XdIou2RqbDbxc5rtMrvShk/lrQZ6uz2Ydm8SgKOoivHFxasuKY1r7u7cXO8Bb1C/8R8pprn2GNFQqauYId9vRnSfC7Cks+CxhF22jwBHgchvGabtXeJSXqhWNoFIoKyrdRoe165C4sp7GkwOTzkgMITo6XFVAsMklyNioiiEHo6Pmo+zoSyU3JYPXgE/xuseZg9RxpN3mLnB+QoZN/AAdCkmk+OaWxkpYVBf40NwTSiysaNWZAxraVPCKUbOOLyNZs9aWB5Q7Glr4x4rgdLuJFjma7oNglP2T78J0JMID8SXWuMCmOxqHLdPFyYgdDY8PvrlqyGKLOkVEOr892SrsBo0uiRSZaB4Aqqdm9W6DrwEfVxOrtrcbeW+1ixFDLPhEyPMeLEUpq61VndAFHElWDqweMkVYv6XKdZ7HpwWc5R04qGBq1kSBYYEuAE+UL5y2h0muBhKoqOZ5pw5I7qAQ3tBWMYlKMnUkSodmF1pmtIBsxC0qqIRzwLynhiKg2yIpGRvpeInEYPYPvVMBDmzP4qdJ1NeNS9PadjnitPFWReNX2ObpliOH/AHxgbXKxLH10WVXpwCajThUdDGi8vOvP2tuV6Xhx/S2l8nOoe1US0Sx2oGSye34sSsvxr+QcrwXvLxEV868v6fgA==
  template:
    metadata:
      name: grafana-secrets
      namespace: mankahi
    type: Opaque
