---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-media
  namespace: mankahi
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgB2g7bW2SAUWSSjozyYsyXVcSS/l7vKYO6IUzJmfv66rAp5NBzB8A6Tvehq5sl0YsUi72KwZzt5Mh2Gd19fYBVbw8fVk8McrTORKpZ3t5GtxmTF4MSNy+ePvk5E5jK+bjdKQzbf3Up6U+fPqD/TlIKlehl67U99cLJcstnzqMekgjWHzBu920XfoY6sOFY2qdC/VJjqKwV6vtZ8gKvkjKEyHhvLoUIHQmG2uWutw8MPUe1sGg/8z+a4f0jHUITeMehx9OmejMR1+J5nwWf+Yz44dn1q570LPJODpB8fDST9AAKsMqOy6gQ+60s3na+YI/MKdhkeewe5xsAgliLnR4pAYTQKbv4G1A8xLargLir5dumS6Cle0TM5XYaVADltjkCfnDVJPMjUU6vb6TbW+c+snbh0AQqtnYZA7pR+FUfv8gIYIje6CgETdOQCovMe3QJ802ZUh10lBB17uomSqeo2ceCipJnGqrll/RBZui7u47ZHgO+AsdY+6UGjBDFWYoZbuK6oDgkKZ/XrHTor2Fvs/9AxGRqeRJfzyw4Ifoe9skAJC6GZoyRO/Fr6m7kqjRO0XjDQ8VIgieGm+eFQQwZcr7zptiAtrd9Td6hZdn7UArQDgX9caSxGNiUbg62MasooJxn6SsnE5iybYWYiEr0nLh0FtF47KMl/t24celB1+LwEuZgKkFjnqAlR8H8IteYFtsjdm9i/gJMD2V5D66NXcq30vr3seOVhgulEioKujD2AM9/WAtml
    MINIO_SECRET_KEY: AgBmGrpQQRXWCMIs4VkgiBkiOwi90u5xKjEzCIP45kSb09seXhdD2zfcu94ZkShpwv4ZDW+naNG/DygbyvdwXJKsKWrX/NhJcDFnMH8jg/WnoKaxEJK5AJfnrF5m+ZQH/Ie6RNCW5fkE9aSWB6yXL0qNqiJiY4Jc/gPE+eFskVo0JSeZ83TkQIADFY9E08b/dfBTKs4xO8u+eEC3BTnPsipUrvMSxWvWePzx7sGQ2ZrTMgJhz7Or17O2sXidnEB0sCvJkboRoQnZmWe7abFrgNQVlTbdjO+W9Nxu8wFGpP3GsVzDWsFq/HtIWM3xR5xx8GFJIDkEeUxS1KNSGna/x/BRUeCRylHebAZo+31RUGnZ4jJDPQgMbUuUk7f318H0UTmsfDt0j6A+E5kN2JZHro7MoSU9XxTofiaXFSEt6Ox18JHYUwah8ajghKitqfZsYfkLkCBMyZ1JO+ReZ0pgTpn8Me+8Y+O/Qe430wQQy3YvsOWiwnWmLlTvTDSsWz/Mipw732eNCpXlVyt3v0XuL8W4/G3Uy+csxx+GL2ZZPBuWc+MGwu8oZV4JpJkmywsI0yCuPDsN264XLTfoheq5pQkVxvY9SUP3a3PabySGBcW+7DYdj3XPk9gwV1dUERzOOENxsWtUcGuKP8vg+XIfFGC56g0rzD3moowXJqWJ4hcQDsElrKUuaLfwDznJ7WB3kHwUk1kqTe+KkLKIMB8OCB432MS/SKT9T/fJ2rwu5OUW4ICrZKj2rrnFippmmQ==
  template:
    metadata:
      name: secret-media
      namespace: mankahi
    type: Opaque
