apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mankahi

resources:
  - ../../base

patchesStrategicMerge:
  []

images:
- name: mankahi/auth-service
  newName: registry.mankahi.local/auth-service
  newTag: stable
- name: mankahi/blog-service
  newName: registry.mankahi.local/blog-service
  newTag: stable
- name: mankahi/analytics-service
  newName: registry.mankahi.local/analytics-service
  newTag: stable
- name: mankahi/admin-service
  newName: registry.mankahi.local/admin-service
  newTag: stable
- name: frontend
  newName: registry.mankahi.local/frontend
  newTag: stable

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ".*"
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 512Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 1000m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 1024Mi
