apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - config.yaml
  - config/environment.yaml
  - secrets/services-secrets.yaml
  - infrastructure.yaml
  - services/auth.yaml
  - ingress.yaml
  - ingress-config.yaml
  - ingress-rbac.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: mankahi
  app.kubernetes.io/instance: mankahi
  app.kubernetes.io/part-of: mankahi-blogging-platform

namespace: mankahi

configMapGenerator:
  - name: shared-config
    envs:
      - .env
