apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - config.yaml
  - infrastructure.yaml
  - services.yaml
  - init-job.yaml
  - frontend.yaml
  - ingress.yaml
  - ingress-config.yaml
  - ingress-rbac.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: mankahi
  app.kubernetes.io/instance: mankahi
  app.kubernetes.io/part-of: mankahi-blogging-platform

namespace: mankahi
