apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
  - target:
      kind: Deployment
      name: elasticsearch
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 3000m
  - target:
      kind: Deployment
      name: redis
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 8Gi
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
  - target:
      kind: Deployment
      name: blog-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1500m
  - target:
      kind: Deployment
      name: analytics-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 50Gi
  - target:
      kind: PersistentVolumeClaim
      name: elasticsearch-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 100Gi

configMapGenerator:
  - name: services-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - REDIS_HOST=prod-redis-service
      - ELASTICSEARCH_NODE=http://prod-elasticsearch-service:9200
      - REDIS_MAX_MEMORY=6gb
      - CACHE_TTL=3600
      - MAX_CONNECTIONS=1000
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX=1000
